--- 
- hosts: all
  sudo: yes

  vars: 
  - mni_packages_url: "http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian"
  - minc_toolkit_pkg: "minc-toolkit-1.0.01-20131211-Ubuntu_12.04-x86_64.deb"
  - cran_mirror_url: "http://cran.utstat.utoronto.ca"

  tasks: 
  - name: Upgrade to latest set of packages
    apt: upgrade=yes update_cache=yes

  - name: Install essential tools
    apt: pkg="{{item}}" state=latest
    with_items: [ git, vim ]

  - name: Install minc dependencies
    apt: pkg="{{item}}" state=latest
    with_items: [libc6, libstdc++6, imagemagick, perl, freeglut3, libgl1-mesa-glx,
                 libxcb1, libxdmcp6, libx11-6, libxext6, libxau6, libuuid1,
                 libjpeg62, libexpat1, libtiff4]

  - name: Fetch minc-toolkit package
    get_url:
      url="{{mni_packages_url}}/{{minc_toolkit_pkg}}"
      dest=/var/cache/apt/archives/

  - name: Install minc-toolkit 
    apt: 
      deb="/var/cache/apt/archives/{{minc_toolkit_pkg}}"
      state=installed 
      update_cache=yes

  - name: Source minc-toolkit on bash startup for all users
    lineinfile: regexp="^source .*minc-toolkit-config" line="source /opt/minc/minc-toolkit-config.sh"
                state=present insertafter=EOF dest=/etc/bash.bashrc

  # R
  - name: Add CRAN apt key
    command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

  - name: Set up CRAN apt repository
    apt_repository: repo="deb {{cran_mirror_url}}/bin/linux/ubuntu precise/" state=present
                    update_cache=yes
  
  - name: Install R base
    apt: pkg="{{item}}" state=latest
    with_items: [ r-base, curl, libcurl4-openssl-dev ]

  - name: Configure a default CRAN mirror for R
    lineinfile: dest=/usr/lib/R/etc/Rprofile.site
                line="options(repos = c(CRAN = '{{cran_mirror_url}}'))"
                regexp="^options(repos")
                state=present insertafter=EOF
 
  - name: Install R packages
    shell: echo "install.packages(c('{{item}}'))"| R --slave --no-save --no-restore-history
    with_items:
        - devtools
